variables:
  - &pogodnik_image git.wearentsa.me/dd/pogodnik:ci

pipeline:

  publish:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      repo: git.wearentsa.me/dd/pogodnik
      tag: ci

  black:
    group: linters
    image: *pogodnik_image
    commands:
      - poetry run black --check .

  isort:
    group: linters
    image: *pogodnik_image
    commands:
      - poetry run isort --check .

  mypy:
    group: linters
    image: *pogodnik_image
    commands:
      - poetry run mypy PoGoDnIk.py src/
