pipeline:
  black:
    group: linters
    image: git.wearentsa.me/dd/pogodnik:add_linters
    commands:
      - poetry run black --check .

  isort:
    group: linters
    image: git.wearentsa.me/dd/pogodnik:add_linters
    commands:
      - poetry run isort --check .

  mypy:
    group: linters
    image: git.wearentsa.me/dd/pogodnik:add_linters
    commands:
      - ls -lla
      - poetry run mypy /app/*.py
