variables:
  - &pogodnik_image git.wearentsa.me/dd/pogodnik:ci

pipeline:

  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: git.wearentsa.me/dd/pogodnik
      registry: git.wearentsa.me
      tag: ci
      username: ${CI_REPO_OWNER}
      password:
        from_secret: docker_password
    when:
      path:
        include: [ 'poetry.lock', 'Dockerfile' ]

  black:
    group: linters
    image: *pogodnik_image
    pull: true
    commands:
      - poetry run black --check .

  isort:
    group: linters
    image: *pogodnik_image
    commands:
      - poetry run isort --check .

  mypy:
    group: linters
    image: *pogodnik_image
    commands:
      - poetry run mypy PoGoDnIk.py src/ --explicit-package-bases

  tests:
    image: *pogodnik_image
    commands:
      - poetry run coverage run -m pytest -v tests/
      - poetry run coverage report -m
